name: Feature
description: Propose a change.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
